database:
  host: localhost
  port: "5432"
  user: postgres
  db-name: db_name
  password: your_password
  ssl-mode: disable

server:
  host: localhost
  port: 8080

nats:
  host: localhost
  port: 4222
